---
title: "R Notebook"
output: html_notebook
---

Customer Churn Analytics 

--------------------------------------------------------------------------------------------------------------------------------------
                                                          #  ALGORITMO 
-------------------------------------------------------------------------------------------------------------------------------------- 

# Nós temos mais de 60 algoritmos de machine learning. 
# O algoritmo nada mais é do que uma sequência de etapas a executar para resolver um determinado problema. 
# Quando executamos um algoritmo de Machine Learning, teremos uma fórmula matemática. 
# Portanto, precisamos preencher esta fórmula matemática com suas variáveis. 

# Para que possamos TREINAR este algoritmo e extrairmos essa função completa
# primeiramente alimentamos o algoritmo com dados e durante o treinamento do algoritmo 
# o algoritmo encontrará os melhores coeficientes que ajudam a complementar essa fórmula matemática. 

# O algoritmo é uma fórmula que preenchemos por parte com dados
# a outra parte da fórmula ele aprenderá sozinho durante o treinamento e então encontrar sozinhos os coeficientes. 
# Ao final do treinamento do algoritmo, nós temos um modelo preditivo:
# uma fórmula matemática já preenchida. A partir disto faremos previsões.
--------------------------------------------------------------------------------------------------------------------------------------
# A rotatividade (churn) de clientes ocorre quando clientes ou assinantes param de fazer negócios com uma empresa ou serviço. 
# Também é conhecido como perda de clientes ou taxa de cancelamento.

# Um setor no qual deseja prever as taxas de cancelamento é o setor de telecomunicações, 
# A maioria dos clientes tem várias opções de escolha dentro de uma localização geográfica.

# Neste projeto, vamos PREVER A ROTATIVIDADE (churn) de clientes usando um conjunto de dados de telecomunicações. 
# Usaremos como modelos de Machine Learning:
- regressão logística
- árvore de decisão 
- floresta aleatória 

# Usaremos um dataset oferecido gratuitamente no portal IBM Sample Data Sets. 
# Cada linha representa um cliente e cada coluna contém os atributos desse cliente.

# https://www.ibm.com/communities/analytics/watson-analytics-blog/guide-to-sample-datasets/

--------------------------------------------------------------------------------------------------------------------------------------

# Carregando os pacotes
install.packages("coorplot")
install.packages("ggthemes")
install.packages("caret")
install.packages("party")

library(plyr)
library(corrplot)
library(ggplot2)
library(gridExtra)
library(ggthemes)
library(caret         # algoritmos para regressão logística e árvores de decisão
library(MASS)
library(randomForest) # pacote para aprendizado de máquina
library(party)        # possui ferramentas de relatório 

--------------------------------------------------------------------------------------------------------------------------------------
                                               # CARREGANDO E LIMPANDO DADOS
--------------------------------------------------------------------------------------------------------------------------------------  

# Os dados brutos contém 7043 linhas (clientes) e 21 colunas (recursos). 
# A coluna "Churn" é o nosso alvo|target|categórica
# Consultar a área de negócios responsável pelos dados para esclarecimento das variáveis preditoras e target
        
churn <- read.csv('Telco-Customer-Churn.csv') # carregar com utils, conjunto de dados pequeno
View(churn)
str(churn)  # tipo das variáveis

--------------------------------------------------------------------------------------------------------------------------------------

# Usamos sapply para verificar o número de valores ausentes (missing) em cada coluna. 
# Descobrimos que há 11 valores ausentes nas colunas "TotalCharges". 
# Então, vamos remover todas as linhas com valores ausentes.
        
sapply(churn, function(x) sum(is.na(x)))
churn <- churn[complete.cases(churn), ]  

--------------------------------------------------------------------------------------------------------------------------------------
       
# Olhe para as variáveis, podemos ver que temos algumas limpezas e ajustes para fazer.
# 1. Vamos mudar "No internet service" para "No" por seis colunas, que são: 
# "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "streamingTV", 
# "streamingMovies".
       
str(churn) 
cols_recode1 <- c(10:15) # aplicando vetor
for(i in 1:ncol(churn[,cols_recode1])) { # aplicando modificação com loop for
  churn[,cols_recode1][,i] <- as.factor(mapvalues
                                        (churn[,cols_recode1][,i], from =c("No internet service"),to=c("No")))
}
--------------------------------------------------------------------------------------------------------------------------------------

# 2. Vamos mudar "No phone service" para "No" para a coluna “MultipleLines”
       
churn$MultipleLines <- as.factor(mapvalues(churn$MultipleLines,  # aplicando mesma alteração, porém em outra coluna
                                           from=c("No phone service"),
                                           to=c("No")))

--------------------------------------------------------------------------------------------------------------------------------------
       
# 3. Como a permanência mínima é de 1 mês e a permanência máxima é de 72 meses, 
# podemos agrupá-los em cinco grupos de posse (tenure): 
# “0-12 Mês”, “12–24 Mês”, “24–48 Meses”, “48–60 Mês” Mês ”,“> 60 Mês”

       
  
       
--------------------------------------------------------------------------------------------------------------------------------------
                                                  # APLICANDO REGRAS DE NEGÓCIO
--------------------------------------------------------------------------------------------------------------------------------------        
       
min(churn$tenure); max(churn$tenure)

group_tenure <- function(tenure){            # grupos de tempo de contrato
  if (tenure >= 0 & tenure <= 12){
    return('0-12 Month')
  }else if(tenure > 12 & tenure <= 24){
    return('12-24 Month')
  }else if (tenure > 24 & tenure <= 48){
    return('24-48 Month')
  }else if (tenure > 48 & tenure <=60){
    return('48-60 Month')
  }else if (tenure > 60){
    return('> 60 Month')
  }
}

churn$tenure_group <- sapply(churn$tenure,group_tenure)
churn$tenure_group <- as.factor(churn$tenure_group)

-------------------------------------------------------------------------------------------------------------------------------------- 
       
# 4. Alteramos os valores na coluna “SeniorCitizen” de 0 ou 1 para ------> “No” ou “Yes”.

churn$SeniorCitizen <- as.factor(mapvalues(churn$SeniorCitizen,
                                           from=c("0","1"),
                                           to=c("No", "Yes")))


--------------------------------------------------------------------------------------------------------------------------------------
       
# 5. Removemos as colunas que não precisamos para a análise.
churn$customerID <- NULL 
churn$tenure <- NULL
View(churn)

       
--------------------------------------------------------------------------------------------------------------------------------------
                                         # ANÁLISE EXPLORATÓRIA DE DADOS E SELEÇÃO DE RECURSO
--------------------------------------------------------------------------------------------------------------------------------------  
      
       
# Correlação entre variáveis numéricas
numeric.var <- sapply(churn, is.numeric) # verificar quais são as variáveis numéricas
corr.matrix <- cor(churn[,numeric.var])  # aplicar a uma matriz de correlação 
       
# Imprimir a matriz de correlação   
corrplot(corr.matrix, main="\n\nGráfico de Correlação para Variáveis Numéricas", method="number")


       
# Os encargos mensais e os encargos totais estão correlacionados. 
# Então, um deles será removido do modelo. Nós removemos Total Charges.
       
churn$TotalCharges <- NULL
       
       
--------------------------------------------------------------------------------------------------------------------------------------
                                                # COMPARANDO VARIÁVEIS CATEGÓRICAS 
--------------------------------------------------------------------------------------------------------------------------------------  

# Gráficos de barra para comparação de variáveis categóricas. Como estão distribuídas e como estão relacionadas
p1 <- ggplot(churn, aes(x=gender)) + ggtitle("Gender") + xlab("Sexo") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p2 <- ggplot(churn, aes(x=SeniorCitizen)) + ggtitle("Senior Citizen") + xlab("Senior Citizen") +        
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p3 <- ggplot(churn, aes(x=Partner)) + ggtitle("Partner") + xlab("Parceiros") +  
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p4 <- ggplot(churn, aes(x=Dependents)) + ggtitle("Dependents") + xlab("Dependentes") +     
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
grid.arrange(p1, p2, p3, p4, ncol=2)

--------------------------------------------------------------------------------------------------------------------------------------
                                                # COMPARANDO VARIÁVEIS CATEGÓRICAS 
--------------------------------------------------------------------------------------------------------------------------------------  
       
# Gráficos de barra para comparação de variáveis categóricas. Como estão distribuídas e como estão relacionadas
p5 <- ggplot(churn, aes(x=PhoneService)) + ggtitle("Phone Service") + xlab("Telefonia") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p6 <- ggplot(churn, aes(x=MultipleLines)) + ggtitle("Multiple Lines") + xlab("Múltiplas Linhas") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p7 <- ggplot(churn, aes(x=InternetService)) + ggtitle("Internet Service") + xlab("Internet Service") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p8 <- ggplot(churn, aes(x=OnlineSecurity)) + ggtitle("Online Security") + xlab("Online Security") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
grid.arrange(p5, p6, p7, p8, ncol=2)

--------------------------------------------------------------------------------------------------------------------------------------
                                                # COMPARANDO VARIÁVEIS CATEGÓRICAS 
--------------------------------------------------------------------------------------------------------------------------------------  
       
# Gráficos de barra para comparação de variáveis categóricas. Como estão distribuídas e como estão relacionadas
p9 <- ggplot(churn, aes(x=OnlineBackup)) + ggtitle("Online Backup") + xlab("Online Backup") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p10 <- ggplot(churn, aes(x=DeviceProtection)) + ggtitle("Device Protection") + xlab("Device Protection") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p11 <- ggplot(churn, aes(x=TechSupport)) + ggtitle("Tech Support") + xlab("Tech Support") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p12 <- ggplot(churn, aes(x=StreamingTV)) + ggtitle("Streaming TV") + xlab("Streaming TV") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
grid.arrange(p9, p10, p11, p12, ncol=2)

--------------------------------------------------------------------------------------------------------------------------------------
                                                # COMPARANDO VARIÁVEIS CATEGÓRICAS 
--------------------------------------------------------------------------------------------------------------------------------------  

# Gráficos de barra para comparação de variáveis categóricas. Como estão distribuídas e como estão relacionadas
p13 <- ggplot(churn, aes(x=StreamingMovies)) + ggtitle("Streaming Movies") + xlab("Streaming Movies") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p14 <- ggplot(churn, aes(x=Contract)) + ggtitle("Contract") + xlab("Contract") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p15 <- ggplot(churn, aes(x=PaperlessBilling)) + ggtitle("Paperless Billing") + xlab("Paperless Billing") + 
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p16 <- ggplot(churn, aes(x=PaymentMethod)) + ggtitle("Payment Method") + xlab("Payment Method") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
p17 <- ggplot(churn, aes(x=tenure_group)) + ggtitle("Tenure Group") + xlab("Tenure Group") +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), width = 0.5) + ylab("Percentual") + coord_flip() + theme_minimal()
       
grid.arrange(p13, p14, p15, p16, p17, ncol=2)
       
# Todas as variáveis categóricas parecem ter uma distribuição razoavelmente ampla, 
# portanto, todas elas serão mantidas para análise posterior. Decisão própria. 
       
--------------------------------------------------------------------------------------------------------------------------------------
                                                  # VARIÁVEL REMOVIDA DA ANÁLISE
--------------------------------------------------------------------------------------------------------------------------------------  
       
# Os encargos mensais e os encargos totais estão correlacionados. 
# Então, um deles será removido do modelo. Nós removemos Total Charges.
       
churn$TotalCharges <- NULL      
            
--------------------------------------------------------------------------------------------------------------------------------------
                                    # MODELAGEM PREDITIVA - CRIANDO MODELO DE MACHINE LEARNING
--------------------------------------------------------------------------------------------------------------------------------------  
       

# Regressão Logística - Algoritmo para classificação 

       
# Primeiro, dividimos os dados em conjuntos de DADOS DE TREINO e DADOS DE TESTE
# Não podemoos usar o memso conjunto de dados para treinar e testar
 
       
# Criando dois datasets       
intrain <- createDataPartition(churn$Churn,p=0.7,list=FALSE) # DataPartition atribuindo 70% dados de treino, restante para dados de teste
training <- churn[intrain,] # usar o índice "intrain" anterior para o TREINO
testing <- churn[-intrain,] # usar o índice "intrain" anterior para o TESTE


# Confirme se a divisão está correta com a função dim() para ver se ambos estão com a mesma distribuição
dim(training)
dim(testing)

--------------------------------------------------------------------------------------------------------------------------------------
                                               # TREINANDO MODELO DE MACHINE LEARNING
--------------------------------------------------------------------------------------------------------------------------------------  
# Treinando o modelo de regressão logística
# Fitting do Modelo
?glm {stats} - função de modelos lineares
       
       
LogModel <- glm(Churn ~ .,                      # variável alvo relacionada com TODAS as outras variáveis do conjunto
                family=binomial(link="logit"),  # parâmetro family para indicar a FUNÇÂO BINOMIAL com "logit" indicando REG. LOGÍSTICA
                data=training)                  # conjunto de dados de treino para realizar treinamento
       
print(summary(LogModel))

--------------------------------------------------------------------------------------------------------------------------------------
                                                    # ANÁLISE DE VARIÂNCIA - ANOVA
                                           # QUAIS VARIÁVEIS SÃO MAIS IMPORTANTE PARA O MODELO
--------------------------------------------------------------------------------------------------------------------------------------  

# Os três principais recursos mais relevantes incluem 
# Contract, tenure_group e PaperlessBilling.
?anova {stats}
anova(LogModel, test="Chisq")
# Executar usando LogModel e teste q-quadrado, listando uma tabela de variâncias
       
       
       
# Analisando a tabela de variância, podemos ver a queda no desvio ao adicionar cada variável. A medida que adicionamos mais variáveis temos uma queda no desvio e variância
       
# Adicionar InternetService, Contract e tenure_group reduz significativamente o desvio residual. 
       
# As outras variáveis, como PaymentMethod e Dependents, parecem melhorar menos o modelo, 
# embora todos tenham valores p baixos. 
       

--------------------------------------------------------------------------------------------------------------------------------------
                                                       # AVALIAÇÃO DO MODELO 
--------------------------------------------------------------------------------------------------------------------------------------  
       
testing$Churn <- as.character(testing$Churn) 
testing$Churn[testing$Churn=="No"] <- "0"
testing$Churn[testing$Churn=="Yes"] <- "1"
fitted.results <- predict(LogModel,newdata=testing,type='response') # Verificar qual é o nível de precisão do modelo
fitted.results <- ifelse(fitted.results > 0.5,1,0)
misClasificError <- mean(fitted.results != testing$Churn)
print(paste('Logistic Regression Accuracy',1-misClasificError))     # Ao final calculamos a acurácia

--------------------------------------------------------------------------------------------------------------------------------------

# Imprimir uma matriz 2x2 de Confusão de Regressão Logística
# Mostra de forma básica como o modelo fez as previsões
print("Confusion Matrix Para Logistic Regression"); table(testing$Churn, fitted.results > 0.5)

       
--------------------------------------------------------------------------------------------------------------------------------------
                                    # MEDIDA DE DESEMPENHO DA REGRESSÃO LOGÍSTICA - ODDS RATIO
--------------------------------------------------------------------------------------------------------------------------------------       
    
# Odds Ratio - medida de avaliação de regularidade do modelo. É a chance de um evento acontecer. 
# Obter este resultado a partir da função exp()

# Uma das medidas de desempenho interessantes na regressão logística é Odds Ratio. 
# Basicamente, odds ratio é a chance de um evento acontecer.
exp(cbind(OR=coef(LogModel), confint(LogModel)))

# Para cada aumento de unidade no encargo mensal (Monthly Charge), 
# há uma redução de 2,5% na probabilidade do cliente cancelar a assinatura.
# Ou seja, quanto maior o valor que o cliente paga, menos propenso ele está de cancelar a sua assinatura.
# Teoricamente o usuário que paga mais tem conhecimento melhor do produto que está pagando e a probabilidade dele cancelar é menor
     
--------------------------------------------------------------------------------------------------------------------------------------
                                               # ALGORITMO DE ÁRVORE DE DECISÃO
--------------------------------------------------------------------------------------------------------------------------------------
     
# Visualização da Árvore de Decisão
# Para fins de ilustração, vamos usar apenas três variáveis para plotar 
# árvores de decisão, elas são “Contrato”, “tenure_group” e “PaperlessBilling”.

?ctree {party}
      # ctree(alvo ~ três variáveis, conjunto de dados de treino)
tree <- ctree(Churn ~ Contract+tenure_group+PaperlessBilling, training)
plot(tree, type='simple')

# 1. Das três variáveis que usamos, o Contrato é a variável mais importante 
# para prever a rotatividade de clientes ou não.
# 2. Se um cliente em um contrato de um ano ou de dois anos, 
# não importa se ele (ela) tem ou não a PapelessBilling, ele (ela) é menos propenso 
# a se cancelar a assinatura.
# 3. Por outro lado, se um cliente estiver em um contrato mensal, 
# e no grupo de posse de 0 a 12 meses, e usando o PaperlessBilling, 
# esse cliente terá mais chances de cancelar a assinatura.


# Matriz de Confusão da Árvore de Decisão
# Estamos usando todas as variáveis para tabela de matriz de confusão de produto e fazer previsões.
       
pred_tree <- predict(tree, testing) # Avaliando previsão com dados de teste|dados novos
print("Confusion Matrix Para Decision Tree"); table(Predicted = pred_tree, Actual = testing$Churn)


# Precisão da árvore de decisão
p1 <- predict(tree, training)
tab1 <- table(Predicted = p1, Actual = training$Churn)
tab2 <- table(Predicted = pred_tree, Actual = testing$Churn)
print(paste('Decision Tree Accuracy',sum(diag(tab2))/sum(tab2)))


--------------------------------------------------------------------------------------------------------------------------------------
                                            # RANDOM FOREST - CONJUNTO PARALELO DE ÁRVORES DE DECISÃO 
--------------------------------------------------------------------------------------------------------------------------------------

# Classificação e regressão com Random Forest
?randomForest {randomForest}
rfModel <- randomForest(Churn ~ ., # Relacionamento de alvo com todas as preditoras
                        data = training) # Aplicando dados de treino
       
print(rfModel) # 100% -  Retorna taxa de erro = acurácia
plot(rfModel)  # Taxa de erro começa alta, cai e chega a um platô

# A previsão é muito boa ao prever "Não". 
# A taxa de erros é muito maior quando se prevê "sim".

# Realizando previsões com dados de teste
pred_rf <- predict(rfModel, testing)

# Executando matriz de confusão 
print("Confusion Matrix Para Random Forest"); table(testing$Churn, pred_rf)
       
--------------------------------------------------------------------------------------------------------------------------------------
                                            # varImpPlot - IMPORTÂNCIA DAS VARIÁVEIS EM randomForest
--------------------------------------------------------------------------------------------------------------------------------------
       
# Recursos mais importantes 
?varImpPlot {randomForest}
varImpPlot(rfModel, sort=T, n.var = 10, main = 'Top 10 Feature Importance')
       
#varImpPlot observará o modleo rfModel criado e buscar quais foram as variáveis mais relevantes para o cálculo da precisão do modelo.
       
--------------------------------------------------------------------------------------------------------------------------------------

# Uma atividade que não está sendo feita é o Deploy do modelo preditivo. Pegar o modelo treinado e avaliado e então fazê-lo realmente realizar as previsões, alimentando o modelo com novos conjuntos de dados para que ele possa prever aquilo que definimos para o projeto. 

